spring.application.name=Auditoria-ISO25010

# Marcação: Configuração da porta do servidor
server.port=8080

# Marcação: Limites de upload (caso haja necessidades de arquivos no futuro)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Marcação: Níveis de log para monitorar o andamento durante a apresentação
logging.level.root=INFO
logging.level.com.org.catolicasc=DEBUG
logging.level.org.springframework.web=INFO